### PR TITLE
Add HTML tutorial

### PR DESCRIPTION
**Pull request by sumith1896**
- Updated to use the new website links
- SciPy -> PyCon
- 2014 -> 2015

/cc @aktech @leosartaj @shivamvats

### CODE REVIEW

**Comment by aktech** [comment]
Is it a complete copy of [this](https://github.com/aktech/sympy-pycon/tree/master/SciPy%20material/tutorial_sphinx)?

**Comment by sumith1896** [comment]
Yes, should be.
What am I missing?
Can you build this or not?

**Comment by aktech** [comment]
I have not tried this on my machine.

> Yes, should be.

I am asking that just to confirm if there are any changes, which I should be looking at.

**Comment by sumith1896** [comment]
It is complete.

**Comment by aktech** [comment]
Lets Merge this first and small changes could be added in an another PR.

**Comment by aktech** [comment]
Thanks @Sumith1896 

Make an another PR for smaller changes.

**Comment by leosartaj** [comment]
Thanks @Sumith1896.

**Pull request merged**
