### PR TITLE
Edited slides.

### PR DESCRIPTION
**Pull request by leosartaj**
I have edited the slides.

Changes:
- Made a new PyCon directory in which we should gradually move stuff as suggested by @Sumith1896. Currently it only has Slides.
- I have added the current ongoing GSoC projects. We can update once we have completed the projects. We should focus on the new features.
- Authors list has not been updated. As the authors list is constantly growing. We can update it before the workshop.
- I have updated sympy-all.txt and sympy-year.txt. These should be updated before the workshop if we decide to show them.
- Not touched the features list. Should be updated before the workshop.
- As the SciPy stuff after authors is not needed, I have commented it out. We can replace it in future. If somebody is giving a talk or with some other SymPy related activity.

We should probably add our names somewhere but I am not very comfortable in renaming the authors. Suggestions?

### CODE REVIEW

**Comment by aktech** [comment]
[This](https://www.sharelatex.com/project/55a4fad866c25f64702565b0) is the final preview, I guess?

**Comment by leosartaj** [comment]
Yes.

**Comment by sumith1896** [comment]
CSymPy changed to SymEngine.
else +1

**Comment by leosartaj** [comment]
Any ideas where we should put our names. New slide? Or leave it for now?

**Comment by sumith1896** [comment]
Maybe add "Presented by SymPy India" below the original authors names

**Comment by leosartaj** [comment]
+1

**Comment by aktech** [comment]
> Maybe add "Presented by SymPy India" below the original authors names

+1

**Comment by leosartaj** [comment]
Ping @aktech @Sumith1896

**Comment by leosartaj** [comment]
Oops not a clean commit.

**Comment by leosartaj** [comment]
Have a look.

**Comment by sumith1896** [comment]
+1

**Comment by shivamvats** [comment]
Looks great!
+1

**Comment by sumith1896** [comment]
Thanks @leosartaj

**Comment by aktech** [comment]
Thanks @leosartaj

**Comment by leosartaj** [comment]
Thanks!

**Pull request merged**
