### PR TITLE
Add Everything to main directory & add .gitignore

### PR DESCRIPTION
**Pull request by aktech**

### CODE REVIEW

**Comment by aktech** [comment]
I have moved everything to main directory.
@Sumith1896

**Comment by sumith1896** [comment]
Do we need everything in main directory?

It would be better if we move relevant things only, then finally remove the SciPy folder itself.
Let me know what you think

**Comment by aktech** [comment]
> It would be better if we move relevant things only, then finally remove the SciPy folder itself.
> Let me know what you think

That sounds good. :+1:

**Comment by aktech** [comment]
Not needed as of now, so Closing.

**Comment by sumith1896** [comment]
Cool, could you create a temporary Gitter channel, it will be easy to correspond.

I don't have SymPy collaborator access, so I can't.

**Comment by sumith1896** [comment]
Do `CREATE ROOM` while on SymPy gitter room

**Comment by aktech** [comment]
Yes Sure, that would be good.

**Comment by aktech** [comment]
Added:  https://gitter.im/sympy/pycon-india

**Pull request closed without merging**
