### PR TITLE
copy ipython notebooks

### PR DESCRIPTION
**Pull request by leosartaj**
Question: is `.ipynb_checkpoints needed`?

### CODE REVIEW

**Comment by sumith1896** [comment]
Afaik no.
It is something that is usually there is the .gitignore.
Feel free to remove them.

**Comment by leosartaj** [comment]
@Sumith1896

**Comment by aktech** [comment]
+1

**Comment by sumith1896** [comment]
+1

**Comment by sumith1896** [comment]
Thanks @leosartaj

**Comment by leosartaj** [comment]
Thanks!

**Pull request merged**
