### PR TITLE
Add Gaurav as Speaker

### LINKED ISSUE #21: Add Gaurav Dhingra to README/Website
@gxyd

### PR DESCRIPTION
**Pull request by gxyd**
fixes #21

### CODE REVIEW

**Comment by aktech** [comment]
Can you add yourself here: http://iamit.in/sympy-tutorial/
Let me know if you need help.

**Comment by gxyd** [comment]
I will try to add myself to the link you mentioned. I couldn't easily see that. But please `Don't` provide hint, right now.

**Comment by aktech** [comment]
@gxyd Sorry, I thought you are not working on the issue, so I added you [there](http://iamit.in/sympy-tutorial/).

**Comment by gxyd** [comment]
It's ok, infact yesterday, when i tried to do this, i found a few new things about github which i didnt' knew, so was enjoying that.

**Comment by aktech** [comment]
Cool! Good to hear that. You probably got to know about `gh-pages`. It's an awesome service by github, I personally like it a lot.

**Comment by gxyd** [comment]
Ya, so you purchased the iamit.in domain name, and the people who visit aktech.github.io are redirected to your domain iamit.in?

**Comment by aktech** [comment]
Yes, exactly.

**Pull request merged**
